---
title: "TAGM Test"
author: "Oliver M. Crook"
date: "23 January 2018"
output: html_document
---

```{r,}
library(sampling)
library(caret)
data("hyperLOPIT2015")
andyhl <- hyperLOPIT2015

andyRes <- bayesgmmCval(object = andyhl, times = 100)

mean(unlist(andyRes$quadloss))

p <- lapply(andyRes$cmlist, function(x) MLInterfaces:::precision(x))
r <- lapply(andyRes$cmlist, function(x) MLInterfaces:::recall(x))
andyF1 <- vector("numeric", length = 100)
for(i in 1:100){
  andyF1[i] <- MLInterfaces:::.macroF1(p[[i]], r[[i]], naAs0 = TRUE)
}
mean(andyF1)

andyf1org <- matrix(0, 100, 14)

for(i in 1:100){
  
  conf <- andyRes$cmlist[[i]]
  
  andyf1 <- MLInterfaces:::F1(conf, naAs0 = TRUE) ## F1 score
  
  andyf1org[i, ] <- andyf1  ##store F1 score

}
andyf1org <- as.data.frame(andyf1org)
colnames(andyf1org) <- getMarkerClasses(andyhl)

gg <- ggplot(data = melt(andyf1org), aes(x=variable, y=value)) + geom_boxplot(aes(fill=variable))
gg <- gg + scale_fill_manual(values=getStockcol(),name = "Organelle/Sub-cellular Compartment")+ theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
gg <- gg + labs(title = "Per organelle F1 scores for mouse stem cell")

w <- table(getMarkers(andyhl, verbose = F))
w <- 1/w[names(w) != "unknown"]
andysvmparams <- svmOptimisation(andyhl, fcol = "markers", times = 100, xval = 5, class.weights = w)

andysvmquadloss <- svmquadloss(svmparam = andysvmparams, object = andyhl)
mean(unlist(andysvmquadloss))

save(andyRes, file = "andyMAPcv.rda")
save(andysvmparams, file = "andysvm.rda")
save(andysvmquadloss, file = "andysvmqloss.rda")



```

```{r,}
data("tan2009r1")
tan2009 <- tan2009r1
fData(tan2009)$markers <- fData(tan2009)$markers.tl

tanres <- bayesgmmCval(object = tan2009, times = 100)

mean(unlist(tanres$quadloss))

p <- lapply(tanres$cmlist, function(x) MLInterfaces:::precision(x))
r <- lapply(tanres$cmlist, function(x) MLInterfaces:::recall(x))
tanF1 <- vector("numeric", length = 100)
for(i in 1:100){
  tanF1[i] <- MLInterfaces:::.macroF1(p[[i]], r[[i]], naAs0 = TRUE)
}
mean(tanF1)

tanf1org <- matrix(0, 100, length(getMarkerClasses(tan2009)))

for(i in 1:100){
  
  conf <- tanres$cmlist[[i]]
  
  tanf1 <- MLInterfaces:::F1(conf, naAs0 = TRUE) ## F1 score
  
  tanf1org[i, ] <- tanf1  ##store F1 score

}
tanf1org <- as.data.frame(tanf1org)
colnames(tanf1org) <- getMarkerClasses(tan2009)

gg1 <- ggplot(data = melt(tanf1org), aes(x=variable, y=value)) + geom_boxplot(aes(fill=variable))
gg1 <- gg1 + scale_fill_manual(values=getStockcol(),name = "Organelle/Sub-cellular Compartment")+ theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
gg1 <- gg1 + labs(title = "Per organelle F1 scores for arabidopsis cell")

w <- table(getMarkers(tan2009, verbose = F))
w <- 1/w[names(w) != "unknown"]
tansvmparams <- svmOptimisation(tan2009, fcol = "markers", times = 100, xval = 5, class.weights = w)

tansvmquadloss <- svmquadloss(svmparam = tansvmparams, object = tan2009)
mean(unlist(tansvmquadloss))

save(tanres, file = "tanMAPcv.rda")
save(tansvmparams, file = "tansvm.rda")
save(tansvmquadloss, file = "tansvmqloss.rda")


```
```{r,}
data("hall2009")
hall2009 <- hall2009

hallres <- bayesgmmCval(object = hall2009, times = 100)

mean(unlist(hallres$quadloss))

p <- lapply(hallres$cmlist, function(x) MLInterfaces:::precision(x))
r <- lapply(hallres$cmlist, function(x) MLInterfaces:::recall(x))
hallF1 <- vector("numeric", length = 100)
for(i in 1:100){
  hallF1[i] <- MLInterfaces:::.macroF1(p[[i]], r[[i]], naAs0 = TRUE)
}
mean(hallF1)

hallf1org <- matrix(0, 100, length(getMarkerClasses(hall2009)))

for(i in 1:100){
  
  conf <- hallres$cmlist[[i]]
  
  hallf1 <- MLInterfaces:::F1(conf, naAs0 = TRUE) ## F1 score
  
  hallf1org[i, ] <- hallf1  ##store F1 score

}
hallf1org <- as.data.frame(hallf1org)
colnames(hallf1org) <- getMarkerClasses(hall2009)

gg1 <- ggplot(data = melt(hallf1org), aes(x=variable, y=value)) + geom_boxplot(aes(fill=variable))
gg1 <- gg1 + scale_fill_manual(values=getStockcol(),name = "Organelle/Sub-cellular Compartment")+ theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
gg1 <- gg1 + labs(title = "Per organelle F1 scores for arabidopsis cell")

w <- table(getMarkers(hall2009, verbose = F))
w <- 1/w[names(w) != "unknown"]
hallsvmparams <- svmOptimisation(hall2009, fcol = "markers", times = 100, xval = 5, class.weights = w)

hallsvmquadloss <- svmquadloss(svmparam = hallsvmparams, object = hall2009)
mean(unlist(hallsvmquadloss))

save(hallres, file = "hallMAPcv.rda")
save(hallsvmparams, file = "hallsvm.rda")
save(hallsvmquadloss, file = "hallsvmqloss.rda")

```
```{r,}
data("hyperLOPITU2OS2017b")
u2oshl <- hyperLOPITU2OS2017b

u2osres <- bayesgmmCval(object = u2oshl, times = 100)

mean(unlist(u2osres$quadloss))

p <- lapply(u2osres$cmlist, function(x) MLInterfaces:::precision(x))
r <- lapply(u2osres$cmlist, function(x) MLInterfaces:::recall(x))
u2osF1 <- vector("numeric", length = 100)
for(i in 1:100){
  u2osF1[i] <- MLInterfaces:::.macroF1(p[[i]], r[[i]], naAs0 = TRUE)
}
mean(u2osF1)

u2osf1org <- matrix(0, 100, length(getMarkerClasses(u2oshl)))

for(i in 1:100){
  
  conf <- u2osres$cmlist[[i]]
  
  u2osf1 <- MLInterfaces:::F1(conf, naAs0 = TRUE) ## F1 score
  
  u2osf1org[i, ] <- u2osf1  ##store F1 score

}
u2osf1org <- as.data.frame(u2osf1org)
colnames(u2osf1org) <- getMarkerClasses(u2oshl)

gg1 <- ggplot(data = melt(u2osf1org), aes(x=variable, y=value)) + geom_boxplot(aes(fill=variable))
gg1 <- gg1 + scale_fill_manual(values=getStockcol(),name = "Organelle/Sub-cellular Compartment")+ theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
gg1 <- gg1 + labs(title = "Per organelle F1 scores for arabidopsis cell")

w <- table(getMarkers(u2oshl, verbose = F))
w <- 1/w[names(w) != "unknown"]
u2ossvmparams <- svmOptimisation(u2oshl, fcol = "markers", times = 100, xval = 5, class.weights = w)

u2ossvmquadloss <- svmquadloss(svmparam = u2ossvmparams, object = u2oshl)
mean(unlist(u2ossvmquadloss))

save(u2osres, file = "u2osMAPcv.rda")
save(u2ossvmparams, file = "u2ossvm.rda")
save(u2ossvmquadloss, file = "u2ossvmqloss.rda")


```

```{r,}
data("itzhak2016stcSILAC")
itzhak <- itzhak2016stcSILAC

itzhak <- filterNA(itzhak)

fData(itzhak)$markers[fData(itzhak)$markers == "ER_high curvature"] <- "unknown"

itzhakres <- bayesgmmCval(object = itzhak, times = 100)

mean(unlist(itzhakres$quadloss))

p <- lapply(itzhakres$cmlist, function(x) MLInterfaces:::precision(x))
r <- lapply(itzhakres$cmlist, function(x) MLInterfaces:::recall(x))
itzhakF1 <- vector("numeric", length = 100)
for(i in 1:100){
  itzhakF1[i] <- MLInterfaces:::.macroF1(p[[i]], r[[i]], naAs0 = TRUE)
}
mean(itzhakF1)

itzhakf1org <- matrix(0, 100, length(getMarkerClasses(itzhak)))

for(i in 1:100){
  
  conf <- itzhakres$cmlist[[i]]
  
  itzhakf1 <- MLInterfaces:::F1(conf, naAs0 = TRUE) ## F1 score
  
  itzhakf1org[i, ] <- itzhakf1  ##store F1 score

}
itzhakf1org <- as.data.frame(itzhakf1org)
colnames(itzhakf1org) <- getMarkerClasses(itzhak)

gg1 <- ggplot(data = melt(itzhakf1org), aes(x=variable, y=value)) + geom_boxplot(aes(fill=variable))
gg1 <- gg1 + scale_fill_manual(values=getStockcol(),name = "Organelle/Sub-cellular Compartment")+ theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
gg1 <- gg1 + labs(title = "Per organelle F1 scores for arabidopsis cell")

w <- table(getMarkers(itzhak, verbose = F))
w <- 1/w[names(w) != "unknown"]
itzhaksvmparams <- svmOptimisation(itzhak, fcol = "markers", times = 100, xval = 5, class.weights = w)

itzhaksvmquadloss <- svmquadloss(svmparam = itzhaksvmparams, object = itzhak)
mean(unlist(itzhaksvmquadloss))

save(itzhakres, file = "itzhakMAPcv.rda")
save(itzhaksvmparams, file = "itzhaksvm.rda")
save(itzhaksvmquadloss, file = "itzhaksvmqloss.rda")

```
```{r,}
data("itzhak2016stcSILAC")
itzhak <- itzhak2016stcSILAC

itzhak <- filterNA(itzhak)
fdata(itzhak)$markers[fdata(itzhak)$markers = "ER_high curvature"] <- "unknown"

itzhakknnparams <- knnOptimisation(itzhak, fcol = "markers", times = 100, xval = 5)

itzhakknnquadloss <- knnquadloss(knnparams = itzhakknnparams, object = itzhak)
mean(unlist(itzhakknnquadloss))

save(itzhakknnparams, file = "itzhakknn.rda")
save(itzhakknnquadloss, file = "itzhakknnqloss.rda")

```

```{r,}
data("hyperLOPITU2OS2017b")
u2oshl <- hyperLOPITU2OS2017b


u2osknnparams <- knnOptimisation(u2oshl, fcol = "markers", times = 100, xval = 5)

u2osknnquadloss <- knnquadloss(knnparams = u2osknnparams, object = u2oshl)
mean(unlist(u2osknnquadloss))

save(u2osknnparams, file = "u2osknn.rda")
save(u2osknnquadloss, file = "u2osknnqloss.rda")

```

```{r,}
data("hyperLOPIT2015")
andyhl <- hyperLOPIT2015


andyknnparams <- knnOptimisation(andyhl, fcol = "markers", times = 100, xval = 5)

andyknnquadloss <- knnquadloss(knnparams = andyknnparams, object = andyhl)
mean(unlist(andyknnquadloss))

save(andyknnparams, file = "andyknn.rda")
save(andyknnquadloss, file = "andyknnqloss.rda")

```
```{r,}
data("tan2009r1")
tan2009 <- tan2009r1
fData(tan2009)$markers <- fData(tan2009)$markers.tl


tanknnparams <- knnOptimisation(tan2009, fcol = "markers", times = 100, xval = 5)

tanknnquadloss <- knnquadloss(knnparams = tanknnparams, object = tan2009)
mean(unlist(tanknnquadloss))

save(tanknnparams, file = "tanknn.rda")
save(tanknnquadloss, file = "tanknnqloss.rda")

```
```{r,}
data("hall2009")
hall2009 <- hall2009


hallknnparams <- knnOptimisation(hall2009, fcol = "markers", times = 100, xval = 5)

hallknnquadloss <- knnquadloss(knnparams = hallknnparams, object = hall2009)
mean(unlist(hallknnquadloss))

save(hallknnparams, file = "hallknn.rda")
save(hallknnquadloss, file = "hallknnqloss.rda")

```
```{r,}
data("itzhak2016stcSILAC")
itzhak <- itzhak2016stcSILAC

itzhak <- filterNA(itzhak)

fData(itzhak)$markers[fData(itzhak)$markers == "ER_high curvature"] <- "unknown"
fData(itzhak)$markers[fData(itzhak)$markers == "Large Protein Complex"] <- "unknown"

itzhakres <- bayesgmmCval(object = itzhak, times = 100)

mean(unlist(itzhakres$quadloss))

p <- lapply(itzhakres$cmlist, function(x) MLInterfaces:::precision(x))
r <- lapply(itzhakres$cmlist, function(x) MLInterfaces:::recall(x))
itzhakF1 <- vector("numeric", length = 100)
for(i in 1:100){
  itzhakF1[i] <- MLInterfaces:::.macroF1(p[[i]], r[[i]], naAs0 = TRUE)
}
mean(itzhakF1)

itzhakresnoLPC <- itzhakres
save(itzhakresnoLPC, file = "itzhakMAPlpccv.rda")


p <- lapply(itzhakcvallpcmcmc$cmlist, function(x) MLInterfaces:::precision(x))
r <- lapply(itzhakcvallpcmcmc$cmlist, function(x) MLInterfaces:::recall(x))
itzhakF1 <- vector("numeric", length = 100)
for(i in 1:100){
  itzhakF1[i] <- MLInterfaces:::.macroF1(p[[i]], r[[i]], naAs0 = TRUE)
}
mean(itzhakF1)


```